# Generated by Django 5.2.17 on 2026-09-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('step_id', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('controls', models.JSONField(default=list, help_text="List of control descriptors, e.g. [{'id': 'buy_ticket', 'type': 'button', 'label': 'Buy Ticket'}]")),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tasks.task')),
            ],
            options={
                'ordering': ['task', 'order'],
                'unique_together': {('task', 'step_id')},
            },
        ),
    ]
