# Generated by Django 5.2.17 on 2026-09-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Optional overall time limit for the task, if any.', null=True),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskstep',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='taskstep',
            name='controls',
            field=models.JSONField(default=list, help_text="List of control descriptors, e.g. [{'id': 'buy_ticket', 'type': 'button', 'label': 'Buy Ticket', 'interaction_type': 'touch'}]"),
        ),
    ]
