# Generated by Django 5.2.17 on 2026-09-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=80, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('resolves_barrier_types', models.JSONField(default=list, help_text='List of barrier_type values this adaptation can resolve.')),
                ('modality', models.CharField(blank=True, help_text="Interaction channel this adaptation primarily uses, e.g. 'visual', 'voice', 'haptic'.", max_length=20)),
                ('accessibility_benefit', models.FloatField(help_text='0-1, how directly this resolves a barrier.')),
                ('interaction_cost', models.FloatField(help_text='0-1, how much this changes the interaction.')),
                ('risk', models.FloatField(help_text='0-1, chance this causes a new problem.')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('allowed_for_tasks', models.JSONField(default=list, help_text="Task ids this may be applied to, or ['*'] for all tasks.")),
                ('ui_effects', models.JSONField(default=dict, help_text="Directives the frontend renderer applies, e.g. {'button_scale': 1.8, 'contrast': 'high', 'flow': 'guided'}.")),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdaptationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('score_breakdown', models.JSONField(default=dict)),
                ('rationale', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('ai', 'AI decision engine'), ('fallback', 'Deterministic fallback')], default='fallback', max_length=10)),
                ('candidates_considered', models.JSONField(default=list)),
                ('approved', models.BooleanField(default=False)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adaptation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='adaptations.adaptation')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
