# Generated by Django 5.2.17 on 2026-09-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adaptations', '0001_initial'),
        ('barriers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaptationresult',
            name='barrier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptation_results', to='barriers.barrier'),
        ),
    ]
