# Generated by Django 5.2.17 on 2026-09-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrier_type', models.CharField(choices=[('small_tap_targets', 'Small tap targets'), ('low_contrast', 'Low contrast / small text'), ('too_many_choices', 'Too many simultaneous choices'), ('audio_only_alert', 'Audio-only alert'), ('fatigue_degraded_precision', 'Fatigue-degraded precision')], max_length=60)),
                ('ability_dimension', models.CharField(max_length=40)),
                ('severity', models.FloatField(help_text='0 (negligible) - 1 (severe).')),
                ('confidence', models.FloatField(help_text='Confidence in the underlying ability signal.')),
                ('evidence', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-severity'],
            },
        ),
    ]
