# Generated by Django 5.2.17 on 2026-09-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='barrier_type',
            field=models.CharField(choices=[('small_tap_targets', 'Small tap targets'), ('low_contrast', 'Low contrast / small text'), ('too_many_choices', 'Too many simultaneous choices'), ('audio_only_alert', 'Audio-only alert'), ('fatigue_degraded_precision', 'Fatigue-degraded precision'), ('controls_out_of_reach', 'Controls outside comfortable reach')], max_length=60),
        ),
    ]
