# Generated by Django 5.2.17 on 2026-09-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barriers', '0004_alter_barrier_barrier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='barrier_type',
            field=models.CharField(choices=[('small_tap_targets', 'Small tap targets'), ('low_contrast', 'Low contrast / small text'), ('too_many_choices', 'Too many simultaneous choices'), ('audio_only_alert', 'Audio-only alert'), ('fatigue_degraded_precision', 'Fatigue-degraded precision'), ('controls_out_of_reach', 'Controls outside comfortable reach'), ('voice_only_input', 'Voice-only / speech-dependent interaction'), ('excessive_interaction_burden', 'Excessive interaction burden')], max_length=60),
        ),
    ]
