# Generated by Django 5.2.17 on 2026-09-17 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Must match an abilities.constants.DIMENSION_KEYS entry.', max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('question_text', models.CharField(max_length=300)),
                ('question_type', models.CharField(choices=[('single_choice', 'Single choice')], default='single_choice', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('options', models.JSONField(default=list, help_text='[{"value": "<ALLOWED_LEVELS[key] entry>", "label": "<display text>"}, ...]')),
            ],
            options={
                'ordering': ['version', 'order'],
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='one_question_per_key_per_version')],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='The question-set version this session was started with.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_value', models.CharField(max_length=60)),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='questionnaire.questionnairequestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaire.questionnairesession')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('session', 'question'), name='one_response_per_question_per_session')],
            },
        ),
    ]
