# Generated by Django 5.2.17 on 2026-09-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment_id', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('source', models.CharField(choices=[('fixture', 'JSON fixture'), ('vision', 'Computer vision analysis')], default='fixture', max_length=20)),
                ('data', models.JSONField(default=dict, help_text='Screen/control layout: controls, contrast, visible_choice_count, audio_alert, noise_level, screen dimensions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
