# Generated by Django 5.2.17 on 2026-09-14 15:39

import abilities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Human-friendly name for demo/selection purposes, e.g. 'Low Vision + Reduced Dexterity'.", max_length=120)),
                ('dimensions', models.JSONField(default=abilities.models.default_dimensions)),
                ('preferred_modality', models.CharField(choices=[('visual', 'Visual'), ('voice', 'Voice'), ('haptic', 'Haptic'), ('visual+haptic', 'Visual + Haptic')], default='visual', max_length=20)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
