# Generated by Django 5.2.17 on 2026-09-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abilityprofile',
            name='preferred_modality',
            field=models.CharField(choices=[('visual', 'Visual'), ('voice', 'Voice'), ('haptic', 'Haptic'), ('mixed', 'Mixed (visual + haptic)')], default='visual', max_length=20),
        ),
    ]
