# Generated by Django 5.2.17 on 2026-09-17 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abilities', '0003_alter_abilityprofile_preferred_modality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_key', models.CharField(choices=[('low_vision_reduced_dexterity', 'Low Vision + Reduced Dexterity'), ('hearing_difficulty', 'Hearing Difficulty'), ('cognitive_load', 'Cognitive Load'), ('limited_mobility_reach', 'Limited Mobility + Reach'), ('speech_difficulty', 'Speech Difficulty'), ('fatigue_reduced_stamina', 'Fatigue / Reduced Stamina'), ('slower_reaction_speed', 'Slower Reaction Speed'), ('visual_hearing_support', 'Visual + Hearing Support'), ('high_interaction_sensitivity', 'High Interaction Sensitivity')], max_length=60)),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('manually_added', 'Manually added')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_selections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['profile_key'],
                'constraints': [models.UniqueConstraint(fields=('user', 'profile_key'), name='one_selection_per_profile_per_user')],
            },
        ),
    ]
