# Generated by Django 5.2.17 on 2026-09-14 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('environments', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('time_seconds', models.PositiveIntegerField(default=0)),
                ('assistance_requested', models.BooleanField(default=False)),
                ('effort', models.PositiveSmallIntegerField(default=3, help_text='Self-reported effort, 1 (low) - 5 (high).')),
                ('confidence', models.PositiveSmallIntegerField(default=3, help_text='Self-reported confidence, 1 (low) - 5 (high).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteractionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Started'), ('analyzed', 'Analyzed'), ('adapted', 'Adapted'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='started', max_length=20)),
                ('ai_used', models.BooleanField(default=False)),
                ('ability_profile_snapshot', models.JSONField(default=dict, help_text='Copy of AbilityProfile.dimensions at session start, for audit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='environments.environment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
