# Generated by Django 5.2.17 on 2026-09-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactionsession',
            name='baseline_mode',
            field=models.BooleanField(default=False, help_text="True = barriers are detected but no adaptation is applied, so this session can feed the 'without AbilityOS' side of the before/after metrics."),
        ),
        migrations.AddField(
            model_name='interactionsession',
            name='is_seed',
            field=models.BooleanField(default=False, help_text='True for demo data created by seed_demo, not a live session.'),
        ),
    ]
