# Generated by Django 5.2.17 on 2026-09-15 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments', '0001_initial'),
        ('feedback', '0003_interactionsession_baseline_mode_and_more'),
        ('tasks', '0002_task_time_limit_seconds_taskstep_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(blank=True, max_length=80)),
                ('event_type', models.CharField(choices=[('step_started', 'Step started'), ('control_selected', 'Control selected'), ('control_reselected', 'Control re-selected (retry)'), ('validation_error', 'Validation error'), ('back_navigation', 'Back navigation'), ('confirmation_opened', 'Confirmation opened'), ('confirmation_completed', 'Confirmation completed'), ('assistance_requested', 'Assistance requested'), ('task_completed', 'Task completed'), ('task_abandoned', 'Task abandoned')], max_length=30)),
                ('control_id', models.CharField(blank=True, max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='adaptation_helpfulness',
            field=models.CharField(blank=True, choices=[('helped', 'Yes, it helped'), ('somewhat_helped', 'Somewhat'), ('did_not_help', 'No, it did not help')], help_text='Only meaningful when an adaptation was actually applied this session.', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ease_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Very difficult'), (2, 'Difficult'), (3, 'Okay'), (4, 'Easy'), (5, 'Very easy')], help_text='1 (very difficult) - 5 (very easy).', null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='optional_comment',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='interactionsession',
            name='assistance_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of explicit assistance-requested events recorded this session.'),
        ),
        migrations.AddField(
            model_name='interactionsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Server timestamp when the session reached a terminal status.', null=True),
        ),
        migrations.AlterField(
            model_name='interactionsession',
            name='baseline_mode',
            field=models.BooleanField(default=False, help_text="True = barriers are detected but no adaptation is applied, so this session can feed the 'without AbilityOS' side of the before/after metrics. Equivalent to Phase 7's 'experience_mode': standard=True, adaptive=False."),
        ),
        migrations.AlterField(
            model_name='interactionsession',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('analyzed', 'Analyzed'), ('adapted', 'Adapted'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('failed', 'Failed')], default='started', max_length=20),
        ),
        migrations.AddIndex(
            model_name='interactionsession',
            index=models.Index(fields=['status'], name='feedback_in_status_30692d_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionsession',
            index=models.Index(fields=['baseline_mode'], name='feedback_in_baselin_fb185a_idx'),
        ),
        migrations.AddIndex(
            model_name='interactionsession',
            index=models.Index(fields=['task', 'status'], name='feedback_in_task_id_f28c6f_idx'),
        ),
        migrations.AddField(
            model_name='interactionevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='feedback.interactionsession'),
        ),
        migrations.AddIndex(
            model_name='interactionevent',
            index=models.Index(fields=['session', 'event_type'], name='feedback_in_session_01d44f_idx'),
        ),
    ]
