# Generated by Django 5.2.17 on 2026-09-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_interactionevent_feedback_adaptation_helpfulness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactionevent',
            name='event_type',
            field=models.CharField(choices=[('step_started', 'Step started'), ('control_selected', 'Control selected'), ('control_reselected', 'Control re-selected (retry)'), ('validation_error', 'Validation error'), ('back_navigation', 'Back navigation'), ('confirmation_opened', 'Confirmation opened'), ('confirmation_completed', 'Confirmation completed'), ('assistance_requested', 'Assistance requested'), ('task_completed', 'Task completed'), ('task_abandoned', 'Task abandoned'), ('interaction_timeout', 'Interaction timed out')], max_length=30),
        ),
    ]
